version: "3.9"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: biblioteca_api

    environment:
      DATABASE_URL: postgresql+psycopg2://usuario:password@ep-xxxx.neon.tech/neondb?sslmode=require
      APP_NAME: Biblioteca Personal API
      APP_VERSION: 2.0.0

    ports:
      - "2603:2603"

    networks:
      - biblioteca_network

    command: >
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 2603"

networks:
  biblioteca_network:
    driver: bridge