"""crear_tabla_usuarios

Revision ID: 82fd915626d5
Revises: a1b2c3d4e5f6
Create Date: 2026-04-17 15:23:51.495052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82fd915626d5'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('foto_perfil', sa.String(length=500), nullable=True),
    sa.Column('avatar_config', sa.Text(), nullable=True),
    sa.Column('bio', sa.String(length=500), nullable=True),
    sa.Column('generos_favoritos', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.add_column('libros', sa.Column('sinopsis', sa.String(length=2000), nullable=True))
    op.add_column('libros', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'libros', 'usuarios', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'libros', type_='foreignkey')
    op.drop_column('libros', 'usuario_id')
    op.drop_column('libros', 'sinopsis')
    op.drop_table('usuarios')
    # ### end Alembic commands ###
